### ISSUE TITLE
canopy.mirage.io Xen unikernel failing to start: Git.Mem.write_pack: wrong checksum

### ISSUE THREAD

**Issue by mato** [mirage/canopy-data#29]
I recently had to reboot the Xen dom0 running http://canopy.mirage.io/, and the unikernel now fails to start for me with the following dumped on the console:

````
2018-05-16 14:52:41 -00:00: INF [git.sync] remote: Total 891 (delta 4), reused 4 (delta 0), pack-reused 881

Unsupported function getrusage called in Mini-OS kernel
2018-05-16 14:52:41 -00:00: INF [git.sync] Received a pack file of 763128 bytes.
2018-05-16 14:52:42 -00:00: WRN [canopy-store] failed pull (Failure
   "Git.Mem.write_pack: wrong checksum.\
  \nExpecting a130cbfa345c7ad9811612c63dd0e0c12321f766, but got d5fdbb8ea77651ff0f974ef87c8d53f8296e184c.")
2018-05-16 14:52:42 -00:00: ERR [application] main: (Invalid_argument ".config/uuid is required in the remote git repository")
Raised at file "pervasives.ml", line 33, characters 20-45
Called from file "src/core/lwt.ml", line 2031, characters 35-40
Re-raised at file "src/core/lwt.ml", line 3008, characters 20-29
Called from file "lib/main.ml", line 60, characters 15-25

Mirage exiting with status 1
````

This is both with the original unikernel binary (which I built on 2017-12-28) and with a new build using a 4.04.2 compiler and latest `Engil/Canopy` `master`.

@hannesm @yomimono @samoht Any ideas what might be causing this? Are any of you still running canopy instances from @Engil's master?

**Comment by yomimono** [comment]
I think @dinosaure and @hannesm had several conversations about this (or a similar) pull failure back in March, which resulted in some patches to `git` which may not yet be released - possibly pinning `git` would help?

**Comment by hannesm** [comment]
what we found out is https://github.com/mirage/ocaml-git/issues/276 -- released git+irmin doesn't work well with git repositories that contain signed commits.  what I did for my canopy instances is to use git repositories where I ensured that they don't contain a signed commit (i needed to squash + rebase, and setup a new repository to get rid of the signed commit in the pack file).  the bug is fixed in git master (of which I'm awaiting a release)..

**Comment by dinosaure** [comment]
Yeah, exactly. Then, you need to `git gc` your repository to delete the old commit (which have the signature) and all works. And then, we need to prepare a beta release of `ocaml-git` indeed.

**Comment by samoht** [comment]
I guess this is a duplicate of https://github.com/Engil/Canopy/issues/84

**Comment by mato** [comment]
I can't do anything to the repository, since `mirage/canopy-data` is a public repository with multiple clones/forks.

@samoht Will the pins in https://github.com/Engil/Canopy/issues/84#issuecomment-389687339 give me a working binary or is that just a pointer to a work in progress?

**Comment by samoht** [comment]
We the pins `irmin-git` (and `irmin-mirage`) should be working properly (at least they pass most of the tests, there is still a minor cache issue somewhere that I need to pin down but that should not impact the semantics).

So if you manage to compile canopy with it, that should fix the current issue.

**Comment by samoht** [comment]
Also, there are not many public forks of that repo: https://github.com/mirage/canopy-data/network and none of them seems up-to-date, so it would probably be ok to just force-push a removal of the signed commits (if @yomimono and @hannesm are ok with "unsigning" their last commits)

**Comment by mato** [comment]
> So if you manage to compile canopy with it, that should fix the current issue.

The pins do compile, however the underlying APIs have changed and I don't know enough about them to fix Canopy's usage. So I'll need help from someone else to look at fixing Canopy to build against the new APIs.

**Comment by cfcs** [comment]
Can't we just wait for the next release of `irmin-git` which implements the correct behaviour?

**Comment by hannesm** [comment]
@cfcs well, it would be nice to have http://canopy.mirage.io online.

@samoht I'm easy in regards to force-pushing and unsigning my last commit(s).  this was done by me using the GitHub editor (instead of my local editor and git commit&&push)

**Comment by yomimono** [comment]
@samoht Same story as Hannes for my commits.

**Comment by dinosaure** [comment]
Hmmhmm, Canopy seems to not follow the last interface of `Irmin`. Currently, I fixed bugs on `ocaml-git` on MirageOS however, I can not test it yet with the current version of Canopy because it does not compile. If someone updated Canopy with the last interface, I will happy to test it.

**Comment by samoht** [comment]
@dinosaure did you try with https://github.com/Engil/Canopy/issues/84 ?

**Comment by dinosaure** [comment]
Finally, Engil/Canopy#96

**Comment by mato** [comment]
Finally, solved by using @dinosaure's `irmin2` branch and some hacks, details at https://github.com/Engil/Canopy/pull/95#issuecomment-543139614. http//canopy.mirage.io/ is up again.
