### ISSUE TITLE
projects page doesn't surface which projects need contributors well

### ISSUE THREAD

**Issue by yomimono** [mirage/canopy-data#8]
One of the main functions of the "pioneer projects" wiki (https://github.com/mirage/mirage-www/wiki/Pioneer-Projects) was a nice summary of which projects need contributors, useful in helping prospective GSoC or Outreachy interns get involved.  The current view of the Projects page, which is apparently intended to replace that wiki, doesn't serve this purpose well.  Can we rearchitect the page such that it's at least clear which projects are suitable targets for students to get involved with?

**Comment by Drup** [comment]
The new one is much more click intensive and quite less readable than the old one. Why was it deprecated ?

**Comment by hannesm** [comment]
Thanks for noticing the unfinished state of the Projects. I just started to get back to that task.

I had hope @mirage/devs would contribute to that effort (mentioned e.g. in http://canopy.mirage.io/irclogs/29-06-2016 and http://canopy.mirage.io/irclogs/24-08-2016).

I just introduced a [`help needed`](http://canopy.mirage.io/tags/help%20needed) tag, and documented the status in mirage to use the [`logs`](http://canopy.mirage.io/Projects/logging) library (it is a help needed page ;)
I also added a [`topkg`](http://canopy.mirage.io/Projects/topkg) (which @samoht showed interest in at the last IRC meeting)
Both pages list packages needing porting, these are likely incomplete (just edit and push to canopy-data) :)

Let me know what you think and how we improve the readability (PRs welcome)
